#! /bin/sh

if [ $# -ne 1 ]
then
    echo "Expecting a single argument which is either Start or stop\n"
    exit 1
fi

case "$1" in
    start)
        echo "Start Loading aesdchar driver"
        aesdchar_load
    ;;
    stop)
        echo "Start Unloading aesdchar driver"
        aesdchar_unload
    ;;
    *)
        echo "Usage: $0 {start|stop}"
        exit 1
esac

exit 0
